name: ritSeq
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bedops
  - bedtools
  - bioconductor-rsubread
  - pyqt
  - qt
  - biopython
  - tqdm
  - blast
  - seaborn
  - adjusttext
  - jupyter
  - jupyter_contrib_nbextensions
  - qgrid
  - bioconductor-edger
  - bioconductor-deseq2
  - rpy2
  - scikit-learn == 0.22
  - missingno
  - stringtie
  - r-psych
  - bioconductor-hybridmtest
  - r-nbclust
  - r-mclust
  - goatools
  - bioconductor-cqn
  - r-repr
  - bioconductor-edaseq
  - r-vctrs
  - r-rlang
  - pip
  - pip:
    - yellowbrick

